version: 1
builder:
	configs:
	- platform: ios
		scheme: Interception
	- platform: macos-xcodebuild
		scheme: Interception
	- platform: tvos
		scheme: Interception
	- platform: watchos
		scheme: Interception

	- documentation_targets:
		- Interception
